nameOverride: ""
fullnameOverride: ""
appVersionOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podLabels:
  component: ""

authorizationPolicy:
  enabled: false

requestAuthentication:
  enabled: false

virtualService:
  routes: []

destinationRule:
  enabled: false
  stableSubsetName: stable
  canarySubsetName: canary

service:
  enabled: false
  port: 8080

configmap:
  enabled: false
  properties:
    PROFILE_ACTIVE: ""
    CHATFLOW_HTTP_URL: ""
    CHATFLOW_HTTPS_URL: ""
    # VERSION: ""

secret:
  enabled: false
  datasource: {}
  awsS3Config: {}
  jwt:
    JWT_SECRET_KEY: "user_token_for_signature_must_be_at_least_256_bits_in_HMAC_signature_algorithms"

rollout:
  enabled: false
  replicaCount: 1
  revisionHistoryLimit: 3
  image:
    repository: chatflow/common
    pullPolicy: IfNotPresent
    tag: "1.0.0"
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
    limits:
      cpu: 300m
      memory: 400Mi
  canary:
    steps: []