# Apigateway Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
spec:
  selector:
    matchLabels:
      category: apigateway
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  revisionHistoryLimit: 8
  template:
    metadata:
      labels:
        category: apigateway
        app: service
    spec:
      containers:
      - name: container
        image: jerry0339/apigateway:1.0.0
      terminationGracePeriodSeconds: 5
---
# Apigateway Service
apiVersion: v1
kind: Service
metadata:
  name: svc-apigateway
spec:
  selector:
    category: apigateway
  ports:
  - port: 8000