# Discovery Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-deployment
spec:
  selector:
    matchLabels:
      category: discovery
  replicas: 1
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  revisionHistoryLimit: 8
  template:
    metadata:
      labels:
        category: discovery
        app: service
    spec:
      containers:
      - name: container
        image: jerry0339/discovery:1.0.0
      terminationGracePeriodSeconds: 5
---
# Discovery Service
apiVersion: v1
kind: Service
metadata:
  name: svc-discovery
spec:
  selector:
    category: discovery
  ports:
  - port: 8761
