# Member Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-deployment
spec:
  selector:
    matchLabels:
      category: member
  replicas: 2
  strategy:
    type: RollingUpdate
  minReadySeconds: 10
  revisionHistoryLimit: 8
  template:
    metadata:
      labels:
        category: member
        app: service
    spec:
      containers:
      - name: container
        image: jerry0339/memberservice:1.0.0
      terminationGracePeriodSeconds: 5
---
# Member Service
apiVersion: v1
kind: Service
metadata:
  name: svc-member
spec:
  selector:
    category: member
  ports:
  - port: 8081