nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

common:
  nameOverride: "fe"
  fullnameOverride: "fe-default"
  appVersionOverride: "1.0.0"

  podLabels:
    component: frontend

  virtualService:
    routes:
      - http.4  # VirtualService.http[*] 블록

  destinationRule:
    enabled: true
    stableSubsetName: stable
    canarySubsetName: canary

  service:
    enabled: true
    port: 3000

  configmap:
    enabled: false

  secret:
    enabled: false

  rollout:
    enabled: true
    replicaCount: 1
    image:
      repository: chatflow/fe
      pullPolicy: IfNotPresent
      tag: ""
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
      limits:
        cpu: 300m
        memory: 400Mi
    canary:
      steps:
        - setCanaryScale:
            replicas: 1
#        - pause: { }
        - setWeight: 10
        - pause:
            duration: 60s
        - setWeight: 30
        - pause:
            duration: 120s
        - setWeight: 100