common:
  fullnameOverride: "fe-prod"

  rollout:
    replicaCount: 1
    image:
      repository: chatflow/fe
      pullPolicy: IfNotPresent
      tag: 1.0.0
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
