common:
  fullnameOverride: "fe-prod"

  rollout:
    replicaCount: 1
    image:
      repository: chatflow/fe
      pullPolicy: IfNotPresent
      tag: 1.0.0
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
      limits:
        cpu: 300m
        memory: 400Mi
