nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

common:
  nameOverride: "notification"
  fullnameOverride: "notification-default"
  appVersionOverride: "1.0.0"

  podLabels:
    component: backend

  virtualService:
    routes:
      - http.2  # VirtualService.http[*] 블록

  destinationRule:
    enabled: true
    stableSubsetName: stable
    canarySubsetName: canary

  service:
    enabled: true
    port: 8080

  configmap:
    enabled: true
    properties:
      PROFILE_ACTIVE: ""
      CHATFLOW_HTTP_URL: ""
      CHATFLOW_HTTPS_URL: ""
      # VERSION: ""

  secret:
    enabled: true
    datasource:
      DB_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      DB_URL: "jdbc:mysql://43.203.119.187:3306/chatflow_notification?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      DB_USERNAME: "snowball"
      DB_PASSWORD: "1234"

  rollout:
    enabled: true
    replicaCount: 1
    image:
      repository: chatflow/notification
      pullPolicy: IfNotPresent
      tag: ""
    resources:
      requests:
        cpu: 200m
        memory: 300Mi
      limits:
        cpu: 300m
        memory: 400Mi
    canary:
      steps:
        - setCanaryScale:
            replicas: 1
        - pause: { }
        - setWeight: 10
        - pause:
            duration: 60s
        - setWeight: 30
        - pause:
            duration: 120s
        - setWeight: 100