
replicaCount: 1

image:
  repository: jerry0339/chatflow-member
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

service:
  nodePort: 31002

configmap:
  data:
    properties:
      profile_active: "dev"
      datasource: "/usr/src/member/datasource/db-info.yaml"

secret:
  data:
    db:
      db-info.yaml: |
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://43.203.119.187:3306/chatflow?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: snowball
        password: 1234