
replicaCount: 1

image:
  repository: jerry0339/chatflow-member
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  limits:
    cpu: 400m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 300Mi

service:
  nodePort: 31002

configmap:
  properties:
    PROFILE_ACTIVE: dev