common:
  fullnameOverride: "dialog-prod"

  configmap:
    properties:
      PROFILE_ACTIVE: prod
      CHATFLOW_HTTP_URL: http://flowchat.shop:30100
      CHATFLOW_HTTPS_URL: https://flowchat.shop:30200

  rollout:
    replicaCount: 1
    image:
      repository: chatflow/dialog
      pullPolicy: IfNotPresent
      tag: 1.0.0
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
