
replicaCount: 2

image:
  repository: chatflow/notification
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  requests:
    cpu: 150m
    memory: 300Mi
  limits:
    cpu: 250m
    memory: 450Mi

service:
  nodePort: 30003

configmap:
  properties:
    PROFILE_ACTIVE: prod
