
replicaCount: 1

image:
  repository: chatflowgcp/chatflow-team
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 150m
    memory: 300Mi

service:
  nodePort: 31003

configmap:
  properties:
    PROFILE_ACTIVE: dev