
replicaCount: 2

image:
  repository: chatflow/chatflow-team
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  requests:
    cpu: 150m
    memory: 300Mi
  limits:
    cpu: 250m
    memory: 450Mi

service:
  nodePort: 30003

configmap:
  properties:
    PROFILE_ACTIVE: prod
    MEMBER_SERVICE_URL: http://flowchat.shop:30002
