
replicaCount: 2

image:
  repository: chatflow/chatflow-team
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  requests:
    cpu: 200m
    memory: 400Mi
  limits:
    cpu: 300m
    memory: 600Mi

service:
  nodePort: 30003

configmap:
  properties:
    PROFILE_ACTIVE: prod
    MEMBER_SERVICE_URL: http://flowchat.shop:30002
