apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "frontend.fullname" . }}-destinationrule
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "frontend.fullname" . }}-stable.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
    - name: {{ .Values.rollouts.destinationRule.stableSubsetName }}
      labels:
        rollouts-pod-template-hash: stable
    - name: {{ .Values.rollouts.destinationRule.canarySubsetName }}
      labels:
        rollouts-pod-template-hash: canary