
replicaCount: 1

image:
  repository: chatflow/fe
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 3000
  nodePort: 30001

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 250m
    memory: 400Mi
  requests:
    cpu: 150m
    memory: 300Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

rollouts:
  steps:
    - setWeight: 0
    - pause:
        duration: 180s
    - setWeight: 10
    - pause: # 수동 대기(무기한 정지) -> pause: {}
        duration: 60s
    - setWeight: 30
    - pause:
        duration: 120s
    - setWeight: 100
  virtualService:
    name: chatflow-routing
    routes:
      - http.4  # VirtualService.http[*] 블록
  destinationRule:
    stableSubsetName: stable
    canarySubsetName: canary