
replicaCount: 2

image:
  repository: jerry0339/chatflow-member
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  limits:
    cpu: 500m
    memory: 600Mi
  requests:
    cpu: 250m
    memory: 300Mi

service:
  nodePort: 30002

configmap:
  properties:
    PROFILE_ACTIVE: prod
