
replicaCount: 2

image:
  repository: chatflow/member
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 8080
  nodePort: 30002

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 250m # 100m = 0.1 CPU 코어
    memory: 500Mi
  requests:
    cpu: 150m
    memory: 300Mi

#startupProbe:
#  httpGet:
#    path: /actuator/startup
#    port: 8080
#  periodSeconds: 5
#  failureThreshold: 24
#livenessProbe:
#  httpGet:
#    path: /actuator/health/liveness
#    port: 8080
#readinessProbe:
#  httpGet:
#    path: /actuator/health/readiness
#    port: 8080

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

#volumeMounts:
#  - name: secret-datasource
#    mountPath: /usr/src/member/datasource
#
#volumes:
#  - name: secret-datasource
#    secret:
#      secretName: chatflow-member-datasource

nodeSelector: {}
tolerations: []
affinity: {}

configmap:
  properties:
    PROFILE_ACTIVE: ""

secret:
  datasource:
    DB_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
    DB_URL: "jdbc:mysql://43.203.119.187:3306/chatflow_member?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
    DB_USERNAME: "snowball"
    DB_PASSWORD: "1234"