
replicaCount: 2

image:
  repository: chatflowgcp/chatflow-member
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 250m
    memory: 500Mi

service:
  nodePort: 30002

configmap:
  properties:
    PROFILE_ACTIVE: prod
