apiVersion: v1
kind: Service
metadata:
  name: notification-app-service
spec:
  type: NodePort 
  selector:
    app: notification-app
  ports:
  - protocol: TCP
    port: 80 # 클러스터 외부에서 접근할 포트 (NodePort 매핑 전)
    targetPort: 8080 # 컨테이너 내부 포트와 매핑
    nodePort: 30010 # NodePort로 사용할 포트 (30000~32767 범위 내에서 선택)
