common:
  fullnameOverride: "member-dev"

  configmap:
    properties:
      PROFILE_ACTIVE: dev

  rollout:
    replicaCount: 1
    image:
      repository: chatflow/member
      pullPolicy: IfNotPresent
      tag: 1.0.0
    resources:
      limits:
        cpu: 250m
        memory: 500Mi
      requests:
        cpu: 150m
        memory: 300Mi
