nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

common:
  nameOverride: "member"
  fullnameOverride: "member-default"
  appVersionOverride: "1.0.0"

  podLabels:
    component: backend

  virtualService:
    routes:
      - http.0  # VirtualService.http[*] 블록

  requestAuthentication:
    enabled: true

  authorizationPolicy:
    secured:
      enabled: true
      rules:
        - paths: [ "/admins/*" ]
          roles: [ "ADMIN" ]
        - paths: [ "/members/*", "/friendships/*" ]
          roles: [ "MEMBER" ]
      defaultAllow:
        enabled: true
        roles: [ "MEMBER", "ADMIN" ]
    public:
      enabled: true
      allowPaths:
        - /sign-up
        - /sign-in
        - /members/swagger
        - /members/swagger-ui.html
      allowRegexPaths:
        - /members/v3/api-docs/.*
        - /members/swagger-ui/.*

  destinationRule:
    enabled: true
    stableSubsetName: stable
    canarySubsetName: canary

  service:
    enabled: true
    port: 8080

  configmap:
    enabled: true
    properties:
      PROFILE_ACTIVE: ""
      CHATFLOW_HTTP_URL: ""
      CHATFLOW_HTTPS_URL: ""
      # VERSION: ""

  secret:
    enabled: true
    datasource:
      DB_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      DB_URL: "jdbc:mysql://43.203.119.187:3306/chatflow_member?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      DB_USERNAME: "snowball"
      DB_PASSWORD: "1234"

  rollout:
    enabled: true
    replicaCount: 2
    image:
      repository: chatflow/member
      pullPolicy: IfNotPresent
      tag: ""
    resources:
      limits:
        cpu: 300m # 100m = 0.1 CPU 코어
        memory: 400Mi
      requests:
        cpu: 200m
        memory: 300Mi
    canary:
      steps:
        - setCanaryScale:
            replicas: 1
        - pause: { }
        - setWeight: 10
        - pause:
            duration: 60s
        - setWeight: 30
        - pause:
            duration: 120s
        - setWeight: 100