nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

common:
  nameOverride: "team"
  fullnameOverride: "team-default"
  appVersionOverride: "1.0.0"

  podLabels:
    component: backend

  virtualService:
    routes:
      - http.1  # VirtualService.http[*] 블록

  destinationRule:
    enabled: true
    stableSubsetName: stable
    canarySubsetName: canary

  service:
    enabled: true
    port: 8080

  configmap:
    enabled: true
    properties:
      PROFILE_ACTIVE: ""
      CHATFLOW_HTTP_URL: ""
      CHATFLOW_HTTPS_URL: ""
      # VERSION: ""

  secret:
    enabled: true
    datasource:
      DB_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
      DB_URL: "jdbc:mysql://43.203.119.187:3306/chatflow_team?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
      DB_USERNAME: "snowball"
      DB_PASSWORD: "1234"
    awsS3Config:
      S3_BUCKET_NAME: ""
      S3_ACCESS_KEY: ""
      S3_SECRET_KEY: ""
      S3_REGION: ""

  rollout:
    enabled: true
    replicaCount: 2
    image:
      repository: chatflow/team
      pullPolicy: IfNotPresent
      tag: ""
    resources:
      limits:
        cpu: 300m
        memory: 400Mi
      requests:
        cpu: 200m
        memory: 300Mi
    canary:
      steps:
        - setCanaryScale:
            replicas: 2
        - pause: { }
        - setWeight: 10
        - pause:
            duration: 60s
        - setWeight: 30
        - pause:
            duration: 120s
        - setWeight: 100

#startupProbe:
#  httpGet:
#    path: /actuator/startup
#    port: 8080
#  periodSeconds: 5
#  failureThreshold: 24
#livenessProbe:
#  httpGet:
#    path: /actuator/health/liveness
#    port: 8080
#readinessProbe:
#  httpGet:
#    path: /actuator/health/readiness
#    port: 8080

#volumeMounts:
#  - name: secret-datasource
#    mountPath: /usr/src/member/datasource
#
#volumes:
#  - name: secret-datasource
#    secret:
#      secretName: chatflow-member-datasource