apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "member.fullname" . }}-properties
  labels:
    {{- include "member.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.properties | nindent 2 }}