apiVersion: v1
kind: Secret
metadata:
  name: {{ include "member.fullname" . }}-datasource
  labels:
    {{- include "member.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.datasource | nindent 2 }}