
replicaCount: 1

image:
  repository: chatflow/dialog
  pullPolicy: IfNotPresent
  tag: 0.0.1

resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    cpu: 200m
    memory: 300Mi

service:
  nodePort: 30004

configmap:
  properties:
    PROFILE_ACTIVE: prod
    MEMBER_SERVICE_URL: http://nps.flowchat.shop:30002
