apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dialog.fullname" . }}-properties
  labels:
    {{- include "dialog.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.properties | nindent 2 }}