apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dialog.fullname" . }}-cred
  labels:
    {{- include "dialog.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.datasource | nindent 2 }}