{{- if .Values.authorizationPolicy.public.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "common.fullname" . }}-authorization-public
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - to:
        - operation:
            paths:
              {{- range .Values.authorizationPolicy.public.allowPaths | default list }}
              - {{ . | quote }}
              {{- end }}
              {{- $root := . }}
              {{- range .Values.authorizationPolicy.public.allowCommonPaths | default list }}
              # (include "common.name" .)로 tpl 접근 가능, 그냥 '.' 사용시 반복문에서는 문자열로 인식하기 때문에 템플릿 전체 context를 변수($root)로 접근
              - {{ printf "/%s%s" (include "common.name" $root) . | quote }}
              {{- end }}
{{- end }}