{{- if .Values.authorizationPolicy.enabled }}
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "common.fullname" . }}-authorization
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - to: # ADMIN 만 허용
        - operation:
            paths: ["/admins/*"]
      when:
        - key: request.auth.claims[role]
          values: ["ADMIN"]
    - to: # MEMBER role만 허용
        - operation:
            paths: ["/members/*", "/friendships/*"]
      when:
        - key: request.auth.claims[role]
          values: ["MEMBER"]
    - from: # 이외 모두 허용
        - source:
            requestPrincipals: ["*"]
      when:
        - key: request.auth.claims[role]
          values: ["MEMBER", "ADMIN"]
{{- end }}