apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-properties
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.properties | nindent 2 }}