{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-properties
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Chart.Name | quote }}
  {{- toYaml .Values.configmap.properties | nindent 2 }}
{{- end }}