{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rollout.replicaCount }}
  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "common.serviceAccountName" . }}
      containers:
        - name: {{ include "common.name" . }}
          envFrom:
            {{- if .Values.configmap.enabled }}
            - configMapRef:
                name: {{ include "common.fullname" . }}-properties
            {{- end }}
            {{- if .Values.secret.enabled }}
            - secretRef:
                name: {{ include "common.fullname" . }}-cred
            {{- end }}
          image: "{{ .Values.rollout.image.repository }}:{{ .Values.rollout.image.tag }}"
          imagePullPolicy: {{ .Values.rollout.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.rollout.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  strategy:
    canary:
      steps:
        {{- toYaml .Values.rollout.canary.steps | nindent 8 }}
      trafficRouting:
        istio:
          virtualService:
            name: {{ .Release.Namespace }}-routing
            routes:
              {{- toYaml .Values.virtualService.routes | nindent 14 }}
          destinationRule:
            name: {{ include "common.fullname" . }}-destinationrule
            canarySubsetName: {{ .Values.destinationRule.canarySubsetName }}
            stableSubsetName: {{ .Values.destinationRule.stableSubsetName }}
{{- end }}