{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.fullname" . }}-cred
  labels:
    {{- include "common.labels" . | nindent 4 }}
stringData:
  {{- with .Values.secret.datasource }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.secret.awsS3Config }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
  {{- with .Values.secret.jwt }}
  {{ toYaml . | nindent 2 }}
  {{- end }}
{{- end }}