apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "team.fullname" . }}-destinationrule
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ include "team.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
    - name: {{ .Values.rollouts.destinationRule.stableSubsetName }}
      labels:
        version: stable
    - name: {{ .Values.rollouts.destinationRule.canarySubsetName }}
      labels:
        version: canary