apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team.fullname" . }}-cred
  labels:
    {{- include "team.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.datasource | nindent 2 }}
  {{- toYaml .Values.secret.awsS3Config | nindent 2 }}
  {{- toYaml .Values.secret.jwt | nindent 2 }}
