apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chatflow-member.fullname" . }}-properties
  labels:
    {{- include "chatflow-member.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configmap.data.properties | nindent 2 }}