apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatflow-member.fullname" . }}-datasource
  labels:
    {{- include "chatflow-member.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secret.data.datasource | nindent 2 }}